export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE'
export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA'
export const FETCH_SEARCH_DATA_SUCCESS = 'FETCH_SEARCH_DATA_SUCCESS'
export const FETCH_SEARCH_DATA_FAIL = 'FETCH_SEARCH_DATA_FAIL'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL'

export const FETCH_NEW_RELEASES = 'FETCH_NEW_RELEASES'
export const FETCH_NEW_RELEASES_SUCCESS = 'FETCH_NEW_RELEASES_SUCCESS'
export const FETCH_NEW_RELEASES_FAIL = 'FETCH_NEW_RELEASES_FAIL'

export const FETCH_CATEGORY_PLAYLISTS = 'FETCH_CATEGORY_PLAYLISTS'
export const FETCH_CATEGORY_PLAYLISTS_SUCCESS =
  'FETCH_CATEGORY_PLAYLISTS_SUCCESS'
export const FETCH_CATEGORY_PLAYLISTS_FAIL = 'FETCH_CATEGORY_PLAYLISTS_FAIL'

export const FETCH_PLAYLIST = 'FETCH_PLAYLIST'
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS'
export const FETCH_PLAYLIST_FAIL = 'FETCH_PLAYLIST_FAIL'

export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK'
