export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE'
export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA'
export const FETCH_SEARCH_DATA_SUCCESS = 'FETCH_SEARCH_DATA_SUCCESS'
export const FETCH_SEARCH_DATA_FAIL = 'FETCH_SEARCH_DATA_FAIL'
