export const SET_SEARCH_PHRASE = 'SET_SEARCH_PHRASE'
export const FETCH_SEARCH_DATA = 'FETCH_SEARCH_DATA'
export const FETCH_SEARCH_DATA_SUCCESS = 'FETCH_SEARCH_DATA_SUCCESS'
export const FETCH_SEARCH_DATA_FAIL = 'FETCH_SEARCH_DATA_FAIL'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL'

export const FETCH_NEW_RELEASES = 'FETCH_NEW_RELEASES'
export const FETCH_NEW_RELEASES_SUCCESS = 'FETCH_NEW_RELEASES_SUCCESS'
export const FETCH_NEW_RELEASES_FAIL = 'FETCH_NEW_RELEASES_FAIL'
